import {
  findConfirmedCustomerReceipt,
  findSucceededProviderOutcome,
  hasContradictionBlockingResolution,
} from "@/src/domain/automation/resolution-evidence-gates";
import { planAutomatedResolutionEvaluation } from "@/src/domain/automation/resolution-policy";
import type { ResolutionCaseBundle } from "@/src/domain/store/model";

export const RESOLUTION_REQUIREMENT_IDS = [
  "provider_transaction_verified",
  "customer_receipt_confirmation",
  "contradictions_resolved",
] as const;

export type ResolutionRequirementId =
  (typeof RESOLUTION_REQUIREMENT_IDS)[number];

export type ResolutionRequirementStatus =
  | "SATISFIED"
  | "MISSING"
  | "BLOCKED";

export type ResolutionRequirement = {
  id: ResolutionRequirementId;
  label: string;
  status: ResolutionRequirementStatus;
  evidenceRefs: string[];
};

export type ResolutionNextAllowedAction =
  | "REQUEST_EVIDENCE"
  | "WAIT_FOR_PROVIDER"
  | "RESOLVE_CONTRADICTION"
  | "ADVANCE_TO_RESOLUTION_PENDING"
  | "REVIEW_FOR_RESOLUTION"
  | "NO_ACTION";

export type ResolutionReadiness = {
  caseId: string;
  caseVersion: number;
  ready: boolean;
  satisfiedRequirements: number;
  totalRequirements: number;
  requirements: ResolutionRequirement[];
  blockingReasons: string[];
  nextAllowedAction: ResolutionNextAllowedAction;
  /** Stored deterministic guidance — not regenerated by WebMCP. */
  currentBlocker: string;
  nextBestAction: string;
  caseState: string;
};

const LABELS: Record<ResolutionRequirementId, string> = {
  provider_transaction_verified: "Provider transaction verified",
  customer_receipt_confirmation: "Customer receipt confirmation",
  contradictions_resolved: "No unresolved claim contradictions",
};

/**
 * Deterministic, non-AI Resolution Readiness projection.
 * Reuses the same evidence gates as planAutomatedResolutionEvaluation.
 */
export function projectResolutionReadiness(
  bundle: ResolutionCaseBundle,
  now: string = new Date().toISOString(),
): ResolutionReadiness {
  const providerOutcome = findSucceededProviderOutcome(bundle);
  const receipt = findConfirmedCustomerReceipt(bundle);
  const contradictionPresent = hasContradictionBlockingResolution(bundle);

  const requirements: ResolutionRequirement[] = [
    {
      id: "provider_transaction_verified",
      label: LABELS.provider_transaction_verified,
      status: providerOutcome ? "SATISFIED" : "MISSING",
      evidenceRefs: providerOutcome
        ? [providerOutcome.evidence.id, providerOutcome.transaction.id]
        : [],
    },
    {
      id: "customer_receipt_confirmation",
      label: LABELS.customer_receipt_confirmation,
      status: receipt ? "SATISFIED" : "MISSING",
      evidenceRefs: receipt ? [receipt.id] : [],
    },
    {
      id: "contradictions_resolved",
      label: LABELS.contradictions_resolved,
      status: contradictionPresent ? "BLOCKED" : "SATISFIED",
      evidenceRefs: contradictionPresent
        ? bundle.claims
            .filter(
              (claim) =>
                claim.status === "CONTRADICTED" ||
                claim.status === "PARTIALLY_VERIFIED",
            )
            .map((claim) => claim.id)
        : [],
    },
  ];

  const evaluation = planAutomatedResolutionEvaluation(bundle, now);
  const ready = evaluation.kind === "MUTATION";
  const blockingReasons: string[] = [];

  if (evaluation.kind === "NO_CHANGE") {
    switch (evaluation.reason) {
      case "STATE_NOT_ELIGIBLE":
        blockingReasons.push(
          `Case state ${bundle.caseRecord.state} is not eligible for automatic resolution (requires RESOLUTION_PENDING).`,
        );
        break;
      case "PROVIDER_OUTCOME_UNKNOWN":
        blockingReasons.push(
          "Succeeded same-case provider-verified refund transaction is missing.",
        );
        break;
      case "CUSTOMER_RECEIPT_UNKNOWN":
        blockingReasons.push(
          "Independently confirmed customer receipt evidence is missing.",
        );
        break;
      case "CONTRADICTION_PRESENT":
        blockingReasons.push(
          "One or more claims remain CONTRADICTED or PARTIALLY_VERIFIED.",
        );
        break;
    }
  }

  const satisfiedRequirements = requirements.filter(
    (requirement) => requirement.status === "SATISFIED",
  ).length;

  const nextAllowedActionInput = {
    ready,
    caseState: bundle.caseRecord.state,
    providerSatisfied: Boolean(providerOutcome),
    receiptSatisfied: Boolean(receipt),
    contradictionPresent,
    ...(evaluation.kind === "NO_CHANGE"
      ? { evaluationReason: evaluation.reason }
      : {}),
  };

  return {
    caseId: bundle.caseRecord.id,
    caseVersion: bundle.caseRecord.version,
    ready,
    satisfiedRequirements,
    totalRequirements: requirements.length,
    requirements,
    blockingReasons,
    nextAllowedAction: deriveNextAllowedAction(nextAllowedActionInput),
    currentBlocker: bundle.caseRecord.currentBlocker,
    nextBestAction: bundle.caseRecord.nextBestAction,
    caseState: bundle.caseRecord.state,
  };
}

function deriveNextAllowedAction(input: {
  ready: boolean;
  evaluationReason?:
    | "STATE_NOT_ELIGIBLE"
    | "PROVIDER_OUTCOME_UNKNOWN"
    | "CUSTOMER_RECEIPT_UNKNOWN"
    | "CONTRADICTION_PRESENT";
  caseState: string;
  providerSatisfied: boolean;
  receiptSatisfied: boolean;
  contradictionPresent: boolean;
}): ResolutionNextAllowedAction {
  if (input.ready) return "REVIEW_FOR_RESOLUTION";
  if (input.contradictionPresent) return "RESOLVE_CONTRADICTION";
  if (!input.providerSatisfied) return "WAIT_FOR_PROVIDER";
  if (!input.receiptSatisfied) return "REQUEST_EVIDENCE";
  if (input.evaluationReason === "STATE_NOT_ELIGIBLE") {
    return input.caseState === "RESOLVED" || input.caseState === "CLOSED"
      ? "NO_ACTION"
      : "ADVANCE_TO_RESOLUTION_PENDING";
  }
  return "NO_ACTION";
}

export type ResolutionGap = {
  type: "MISSING_EVIDENCE" | "CONTRADICTION" | "STATE_GATE";
  requirement: ResolutionRequirementId | "case_state";
  reason: string;
  nextAllowedAction: ResolutionNextAllowedAction;
};

export function listResolutionGaps(
  readiness: ResolutionReadiness,
): ResolutionGap[] {
  const gaps: ResolutionGap[] = [];
  for (const requirement of readiness.requirements) {
    if (requirement.status === "SATISFIED") continue;
    if (requirement.id === "contradictions_resolved") {
      gaps.push({
        type: "CONTRADICTION",
        requirement: requirement.id,
        reason:
          readiness.blockingReasons.find((reason) =>
            reason.includes("CONTRADICTED"),
          ) ?? "Claim contradictions block deterministic resolution.",
        nextAllowedAction: "RESOLVE_CONTRADICTION",
      });
      continue;
    }
    gaps.push({
      type: "MISSING_EVIDENCE",
      requirement: requirement.id,
      reason:
        requirement.id === "provider_transaction_verified"
          ? "Succeeded same-case provider-verified refund transaction is missing."
          : "Independently confirmed customer receipt evidence is missing.",
      nextAllowedAction:
        requirement.id === "provider_transaction_verified"
          ? "WAIT_FOR_PROVIDER"
          : "REQUEST_EVIDENCE",
    });
  }
  if (
    !readiness.ready &&
    readiness.caseState !== "RESOLUTION_PENDING" &&
    readiness.requirements.every((requirement) => requirement.status === "SATISFIED")
  ) {
    gaps.push({
      type: "STATE_GATE",
      requirement: "case_state",
      reason: `Case state ${readiness.caseState} is not eligible for automatic resolution.`,
      nextAllowedAction: readiness.nextAllowedAction,
    });
  }
  return gaps;
}
